### ISSUE TITLE
not an issue - a query

### ISSUE THREAD

**Issue by ajitha3008** [njovy/AppRTCDemo#1]
hi,

first I would like to appreciate the work you have been doing. APPRTC demo is very much useful to me. I would like to know if yu have come across any android native client using signaling.simplewebrtc.com signaling server...or have yu tried to do so? I tried to hit the server and facing issue. I tried to use it with socket io wrapper... also if there is source code for apprtc signaling server in github, I would love to have the github link.

Thanks.

**Comment by njovy** [comment]
I haven't tried any demo from signaling.simplewebrtc.com. I built a signaling server based on apprtc as this sample project gave me an idea where to begin with. Plus, this AppRTC for Android works without any modification with the AppRTC server.
The apprtc repo is available here https://github.com/webrtc/apprtc.

**Comment by ajitha3008** [comment]
Thanks njovy... Great work :)
