### ISSUE TITLE
libjingle_peerconnection_so x86 support

### ISSUE THREAD

**Issue by dejanGH** [njovy/AppRTCDemo#10]
It would be nice to have x86 libjingle_peerconnection_so library included in project

**Comment by njovy** [comment]
I will include x86 and x64 libjingle in the next commit!

**Comment by lkevin029** [comment]
in what site did you get that libjingle_peerconnection_so and libjingle_peerconnection.jar?

**Comment by njovy** [comment]
@lkevin029 I built webrtc on my own linux machine.
You can get the source code and build it from [here](https://webrtc.org/native-code/android/ )

**Comment by TheChuckster** [comment]
Hey dejanGH, if you need help building WebRTC, send me a private message. It's about a 10 hour process if you don't know what you are doing.

**Comment by njovy** [comment]
@dejanGH I've updated the repo and x86 is included.

**Comment by dejanGH** [comment]
@njovy  thanks :)

**Comment by njovy** [comment]
@TheChuckster Have you experienced this [issue] (https://bugs.chromium.org/p/webrtc/issues/detail?id=5600) by any chance?

**Comment by TheChuckster** [comment]
@njovy No, I have not, but the last time I ran AppRTC on the apprtc appspot domain was over a week ago. I'm currently writing my own websockets signalling server from scratch.

**Comment by dejanGH** [comment]
@TheChuckster  local AppRTC server doesn't solve the issue
