### ISSUE TITLE
( dialogic xms server )SDP exception inside onRemoteDescription on peerConnectionClient.setRemoteDescription(sdp);

### ISSUE THREAD

**Issue by AnthonyKoueik** [njovy/AppRTCDemo#2]
Hello i am trying to make a call on Dialogic WebRTC demo , when i a create offer the call is received and everything is Ok

but i get the sdp and i try to set the remote desc (peerConnectionClient.setRemoteDescription(sdp);)

i get exception whether  on receiving offer 
07-29 13:31:07.402    7137-7290/com.koa.test W/libjingle﹕ max-bundle specified without BUNDLE specified
07-29 13:31:07.402    7137-7290/com.koa.test E/libjingle﹕ Failed to set remote offer sdp: Failed to create channels.
07-29 13:31:07.402    7137-7290/com.koa.test E/PCRTCClient﹕ Peerconnection error: setSDP error: Failed to set remote offer sdp: Failed to create channels.

and when receiving Answer

sdp WRONG_CONTENT exception.

**Comment by njovy** [comment]
It looks like SDP using Dialogic is not same as AppRTC(https://apprtc.appspot.com/). I am not familiar with Dialogic but I think you need to use a library provided by this vendor to be able to fix this problem or you can change the format of SDP to communicate correctly with the server. I had no problem with AppRTC using this demo so I am closing this issue.
