### ISSUE TITLE
"libjingle_peerconnection_so.so" has unexpected e_machine: 40

### ISSUE THREAD

**Issue by nadia14** [njovy/AppRTCDemo#23]
After the update to the latest WebRTC version , I can't run the app on 86X emulators anymore .
I always get this error : 

java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/webrtcandroid-2/lib/x86/libjingle_peerconnection_so.so" has unexpected e_machine: 40
                                                                         at java.lang.Runtime.loadLibrary(Runtime.java:372)

Is it a problem with the build?

**Comment by notedit** [comment]
i use the this project's lib, but with no lucky.

i build my self   https://github.com/notedit/libWebRTC-Android

**Comment by nadia14** [comment]
@notedit  thanks  it works . However is it  the 13545 version ?  since i had to make one tweak to the code  for it to compile .

**Comment by notedit** [comment]
2016-07-20  base code,  i don't know the  exact  version. 

i  will   update  to the  latest version  next week.

**Comment by njovy** [comment]
@nadia14 Try the latest repo which is [r13665](https://chromium.googlesource.com/external/webrtc/+/968c9ccfe80f6f0d64991d5e997ce74774381dfa).

**Comment by nadia14** [comment]
@njovy  I tried the latest lib , the error disappeared . thanks
