### ISSUE TITLE
Streaming getting disconnected after around 40 seconds and black white video 

### ISSUE THREAD

**Issue by niteshgarg** [njovy/AppRTCDemo#3]
Hi, 

Thanks for putting up this app. 

We tried to port this app on google glass and getting 2 issues ; 
1. Glass is streaming black and white video 
2. Stream gets disconnected after a period of around 40 seconds with below logs : 

32540-4504/com.oneminuut.genzo E/libjingle﹕ webrtc: (process_thread_impl.cc:31): TimeUntilNextProcess returned an invalid value -25
07-31 23:11:44..
[31-07-2015 23:13:36] Triloki Nath Yadav:  32540-32540/com.oneminuut.genzo E/IStream﹕ Start of onStart
07-31 23:11:45.977   32540-1153/com.oneminuut.genzo A/libc﹕ Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 1153 (Binder_3)
07-31 23:11:48.852      498-525/? E/InputDispatcher﹕ channel '420cbe30 com.oneminuut.genzo/com.oneminuut.genzo.VideoAssistActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
07-31 23:11:48.907      498-525/? E/InputDispatcher﹕ channel '42208b18 com.oneminuut.genzo/org.appspot.apprtc.CallActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

[9189-9330/com.oneminuut.genzo E/WEBRTC﹕ ERROR     ; (23:15:27:622 |  525)                                9330; (process_thread_impl.cc:31): TimeUntilNextProcess returned an invalid value -4
07-31 23:15:28.008    9189-9241/com.oneminuut.genzo E/WEBRTC﹕ ERROR     ; (23:15:28: 14 |    0)                                9241; (voe_audio_processing_impl.cc:1007): SetTypingDetectionStatus: not supported
07-31 23:15:28.110    9189-9242/com.oneminuut.genzo E/libjingle﹕ SetAudioSend: No audio channel exists.
07-31 23:15:28.118    9189-9242/com.oneminuut.genzo E/libjingle﹕ SetAudioPlayout: No audio channel exists.

Kindly see if you can help us. 

Many Thanks,
Nitesh

**Comment by njovy** [comment]
I haven't tried this demo on google glass so it's tough for me to tell what caused an error. This repo is not an official repository of webrtc so I would recommend you to go on this group https://groups.google.com/forum/#!forum/discuss-webrtc and post your error there. There are webrtc maintainers and developers using webrtc in this group so they might help you there!
