### ISSUE TITLE
missing Logging.java and ThreadUtils.java

### ISSUE THREAD

**Issue by ggggxiaolong** [njovy/AppRTCDemo#38]
some java file are missed, you can find it in [new pull request](https://github.com/njovy/AppRTCDemo/pull/33) or [there](https://github.com/RWebRTC/WebRTC-Android-Learn/blob/master/RAppRTC/app/libs/base_java.jar), source directory [webrtc/base/java/src/org/webrtc]

**Comment by njovy** [comment]
Oops. base_java.jar is missing.
The latest repo has it now.
