### ISSUE TITLE
Many to many WebRTC

### ISSUE THREAD

**Issue by ShkurtiA** [njovy/AppRTCDemo#5]
Hello,

I am studying your example and I have a question. How can I use this example to implement Many to Many WebRTC connection, if possible of course?

Thanks

**Comment by njovy** [comment]
Group video call is doable with WebRTC on Android and you can check examples from here to see how you starts. https://www.webrtc-experiment.com/#multi-user
I never needed a group video call so I don't have any tips for that sorry!
