### ISSUE TITLE
bad request

### ISSUE THREAD

**Issue by zhanglinlovejava** [njovy/AppRTCDemo#8]
Room IO error: java.io.IOException: Non-200 response when requesting TURN server from https://computeengineondemand.appspot.com/turn?username=79039869&key=4080218913 : HTTP/1.1 400 Bad Request   ------do you know why?thank you very much!

**Comment by njovy** [comment]
It seems like Google no longer provides a free TURN server. The TURN server was down for a while (more than a week).

**Comment by njovy** [comment]
I created a new branch which uses STUN servers since https://computeengineondemand.appspot.com/turn doesn't work. It won't throw an Exception!

**Comment by nikhilkilivayil** [comment]
Getting the same here. What I need to fix do for fixing this issue?

**Comment by njovy** [comment]
@nikhilkilivayil  TURN servers provided Google isn't available 24/7. Take a look at [stun-server] (https://github.com/njovy/AppRTCDemo/tree/stun-server) branch and you can test it using a STUN server.

**Comment by nikhilkilivayil** [comment]
Ok.resolved my issue.
